`timescale 1ns/1ps

// Test wrapper: decode_stage + pipeline_reg_ID_EX wired together.
// Simulation only — not part of the final SoC.
module decode_id_ex_wrap (
    input  logic        clk,
    input  logic        rst,
    input  logic        stall_i,
    input  logic        flush_i,

    // Decode stage inputs
    input  logic [31:0] instr_i,
    input  logic [31:0] pc_i,
    input  logic [31:0] rs1_data_i,
    input  logic [31:0] rs2_data_i,

    // Decode stage combinational outputs (visible without clock)
    output logic [4:0]  rs1_o,
    output logic [4:0]  rs2_o,
    output logic [4:0]  rd_o,
    output logic [2:0]  funct3_o,
    output logic [31:0] rs1_data_o,
    output logic [31:0] rs2_data_o,
    output logic [31:0] imm_o,
    output logic [31:0] pc_o,
    output logic        reg_write_o,
    output logic        mem_read_o,
    output logic        mem_write_o,
    output logic        alu_src_b_o,
    output logic        alu_src_a_o,
    output logic        branch_o,
    output logic        jump_o,
    output logic [3:0]  alu_ctrl_o,
    output logic [1:0]  wb_sel_o,

    // ID/EX pipeline register outputs (clocked)
    output logic        reg_write_ex_o,
    output logic        mem_read_ex_o,
    output logic        mem_write_ex_o,
    output logic        alu_src_b_ex_o,
    output logic        alu_src_a_ex_o,
    output logic        branch_ex_o,
    output logic        jump_ex_o,
    output logic [3:0]  alu_ctrl_ex_o,
    output logic [1:0]  wb_sel_ex_o,
    output logic [2:0]  funct3_ex_o,
    output logic [31:0] rs1_data_ex_o,
    output logic [31:0] rs2_data_ex_o,
    output logic [31:0] imm_ex_o,
    output logic [31:0] pc_ex_o,
    output logic [4:0]  rs1_ex_o,
    output logic [4:0]  rs2_ex_o,
    output logic [4:0]  rd_ex_o
);
    decode_stage u_decode (
        .instr_i      (instr_i),
        .pc_i         (pc_i),
        .rs1_data_i   (rs1_data_i),
        .rs2_data_i   (rs2_data_i),
        .rs1_o        (rs1_o),
        .rs2_o        (rs2_o),
        .rd_o         (rd_o),
        .funct3_o     (funct3_o),
        .rs1_data_o   (rs1_data_o),
        .rs2_data_o   (rs2_data_o),
        .imm_o        (imm_o),
        .pc_o         (pc_o),
        .reg_write_o  (reg_write_o),
        .mem_read_o   (mem_read_o),
        .mem_write_o  (mem_write_o),
        .alu_src_b_o  (alu_src_b_o),
        .alu_src_a_o  (alu_src_a_o),
        .branch_o     (branch_o),
        .jump_o       (jump_o),
        .alu_ctrl_o   (alu_ctrl_o),
        .wb_sel_o     (wb_sel_o)
    );

    pipeline_reg_ID_EX u_id_ex (
        .clk          (clk),
        .rst          (rst),
        .stall_i      (stall_i),
        .flush_i      (flush_i),
        .reg_write_i  (reg_write_o),
        .mem_read_i   (mem_read_o),
        .mem_write_i  (mem_write_o),
        .alu_src_b_i  (alu_src_b_o),
        .alu_src_a_i  (alu_src_a_o),
        .branch_i     (branch_o),
        .jump_i       (jump_o),
        .alu_ctrl_i   (alu_ctrl_o),
        .wb_sel_i     (wb_sel_o),
        .funct3_i     (funct3_o),
        .rs1_data_i   (rs1_data_o),
        .rs2_data_i   (rs2_data_o),
        .imm_i        (imm_o),
        .pc_i         (pc_o),
        .rs1_i        (rs1_o),
        .rs2_i        (rs2_o),
        .rd_i         (rd_o),
        .reg_write_o  (reg_write_ex_o),
        .mem_read_o   (mem_read_ex_o),
        .mem_write_o  (mem_write_ex_o),
        .alu_src_b_o  (alu_src_b_ex_o),
        .alu_src_a_o  (alu_src_a_ex_o),
        .branch_o     (branch_ex_o),
        .jump_o       (jump_ex_o),
        .alu_ctrl_o   (alu_ctrl_ex_o),
        .wb_sel_o     (wb_sel_ex_o),
        .funct3_o     (funct3_ex_o),
        .rs1_data_o   (rs1_data_ex_o),
        .rs2_data_o   (rs2_data_ex_o),
        .imm_o        (imm_ex_o),
        .pc_o         (pc_ex_o),
        .rs1_o        (rs1_ex_o),
        .rs2_o        (rs2_ex_o),
        .rd_o         (rd_ex_o)
    );

endmodule
