`timescale 1ns/1ps

// RV32IM M-extension co-processor.
// MUL/MULH/MULHSU/MULHU: combinational result, no stall.
// DIV/DIVU/REM/REMU:      latched operands, 32-cycle stall, behavioral result.
//
// start_i: 1-cycle pulse generated by riscv_core on the first cycle an
//           M-ext instruction is active in EX and the pipeline is not stalled.
//           A mext_prev_stall flip-flop in riscv_core prevents re-triggering
//           on the cycle immediately after mext_stall de-asserts.
//
// funct3 encoding (funct7 == 7'b000_0001 on all M-ext):
//   000=MUL  001=MULH  010=MULHSU  011=MULHU
//   100=DIV  101=DIVU  110=REM     111=REMU
module mext_unit (
    input  logic        clk,
    input  logic        rst,

    // Forwarded operands from execute_stage (valid on start_i and held during stall)
    input  logic [31:0] rs1_i,
    input  logic [31:0] rs2_i,
    input  logic [2:0]  funct3_i,

    // 1-cycle start pulse from riscv_core
    input  logic        start_i,

    // Result and stall outputs
    output logic [31:0] result_o,
    output logic        stall_o
);

    // -------------------------------------------------------------------------
    // MUL family — combinational 64-bit products, no stall
    // -------------------------------------------------------------------------
    // Icarus compat: signed casts extracted to assigns outside always_comb.
    logic signed [31:0] rs1_sgn, rs2_sgn;
    assign rs1_sgn = rs1_i;
    assign rs2_sgn = rs2_i;

    logic signed [63:0] mul_ss;   // MULH:   signed × signed
    logic        [63:0] mul_uu;   // MULHU:  unsigned × unsigned

    assign mul_ss = rs1_sgn * rs2_sgn;
    assign mul_uu = {32'b0, rs1_i} * {32'b0, rs2_i};

    // MULHSU: upper32(signed(rs1) × unsigned(rs2))
    // Identity: MULHSU(a,b) = MULHU(a,b) - (a[31] ? b : 0)
    logic [31:0] mulhsu_hi;
    assign mulhsu_hi = mul_uu[63:32] - (rs1_i[31] ? rs2_i : 32'b0);

    // MUL result (combinational, uses live rs1_i/rs2_i)
    logic [31:0] mul_result;
    always_comb begin
        case (funct3_i)
            3'b000:  mul_result = mul_ss[31:0];    // MUL  — lower 32
            3'b001:  mul_result = mul_ss[63:32];   // MULH — upper 32 signed×signed
            3'b010:  mul_result = mulhsu_hi;        // MULHSU
            3'b011:  mul_result = mul_uu[63:32];   // MULHU — upper 32 unsigned×unsigned
            default: mul_result = 32'b0;
        endcase
    end

    // -------------------------------------------------------------------------
    // DIV/REM family — latch operands, count 32 cycles, behavioral result
    // -------------------------------------------------------------------------
    logic [31:0] div_rs1, div_rs2;
    logic [2:0]  div_funct3;
    logic        counting;
    logic [4:0]  count;

    always_ff @(posedge clk) begin
        if (rst) begin
            counting   <= 1'b0;
            count      <= 5'b0;
            div_rs1    <= 32'b0;
            div_rs2    <= 32'b0;
            div_funct3 <= 3'b0;
        end else if (counting) begin
            if (count == 5'd31) counting <= 1'b0;
            else                count    <= count + 5'd1;
        end else if (start_i && funct3_i[2]) begin
            div_rs1    <= rs1_i;
            div_rs2    <= rs2_i;
            div_funct3 <= funct3_i;
            counting   <= 1'b1;
            count      <= 5'b0;
        end
    end

    assign stall_o = counting;

    // -------------------------------------------------------------------------
    // DIV/REM combinational result (uses latched operands)
    // RV32M edge cases:
    //   Divide by zero:   quotient = 0xFFFF_FFFF, remainder = dividend
    //   INT_MIN / -1:     quotient = INT_MIN,      remainder = 0
    // -------------------------------------------------------------------------
    // Icarus compat: signed operands as assigns outside always_comb.
    logic signed [31:0] div_rs1_sgn, div_rs2_sgn;
    assign div_rs1_sgn = div_rs1;
    assign div_rs2_sgn = div_rs2;

    logic div_by_zero, div_overflow;
    assign div_by_zero  = (div_rs2 == 32'b0);
    assign div_overflow = (div_rs1 == 32'h8000_0000) && (div_rs2 == 32'hFFFF_FFFF);

    logic [31:0] div_result;
    always_comb begin
        case (div_funct3)
            3'b100: begin  // DIV — signed quotient
                if      (div_by_zero)   div_result = 32'hFFFF_FFFF;
                else if (div_overflow)  div_result = 32'h8000_0000;
                else                    div_result = div_rs1_sgn / div_rs2_sgn;
            end
            3'b101: begin  // DIVU — unsigned quotient
                if (div_by_zero)        div_result = 32'hFFFF_FFFF;
                else                    div_result = div_rs1 / div_rs2;
            end
            3'b110: begin  // REM — signed remainder
                if      (div_by_zero)   div_result = div_rs1;
                else if (div_overflow)  div_result = 32'b0;
                else                    div_result = div_rs1_sgn % div_rs2_sgn;
            end
            3'b111: begin  // REMU — unsigned remainder
                if (div_by_zero)        div_result = div_rs1;
                else                    div_result = div_rs1 % div_rs2;
            end
            default:                    div_result = 32'b0;
        endcase
    end

    // -------------------------------------------------------------------------
    // Output mux: MUL is combinational, DIV uses latched result
    // -------------------------------------------------------------------------
    assign result_o = funct3_i[2] ? div_result : mul_result;

endmodule
