#!/usr/bin/env python3
"""
gen_weights_numpy.py — generate a synthetic weights.h for simulation without PyTorch.

Produces INT8 weight arrays and INT32 biases in the exact format that quantize.py
would emit after training, allowing benchmark.c and mnist/main.c to compile and
run in Verilator simulation without a real trained model.

The weights are seeded deterministically so the output is reproducible.  They do
NOT give meaningful MNIST accuracy — use train_mnist.py + quantize.py for real
inference.  This script is only for compile/simulation validation.

Usage:
    python3 tools/gen_weights_numpy.py            # writes sw/weights.h
    python3 tools/gen_weights_numpy.py --output path/to/weights.h
"""

import argparse
import os
import sys
import numpy as np

SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT  = os.path.join(os.path.dirname(SCRIPT_DIR), "sw", "weights.h")

# Network shape: matches MnistMLP in train_mnist.py
LAYERS = [
    ("fc1",  784, 128),   # (name, in_features, out_features)
    ("fc2",  128,  10),
]


def quantize_tensor(arr: np.ndarray):
    """Symmetric INT8 quantization — matches quantize.py exactly."""
    max_val = float(np.abs(arr).max())
    if max_val == 0.0:
        return arr.astype(np.int8), 1.0
    scale   = max_val / 127.0
    q       = np.clip(np.round(arr / scale), -128, 127).astype(np.int8)
    return q, scale


def emit_int8(f, name, data):
    f.write(f"static const int8_t {name}[] = {{\n")
    flat = data.flatten()
    for i, v in enumerate(flat):
        if i % 16 == 0:
            f.write("    ")
        f.write(f"{int(v):4d},")
        if (i + 1) % 16 == 0:
            f.write("\n")
    if len(flat) % 16 != 0:
        f.write("\n")
    f.write("};\n\n")


def emit_int32(f, name, data):
    f.write(f"static const int32_t {name}[] = {{\n")
    flat = data.flatten()
    for i, v in enumerate(flat):
        if i % 8 == 0:
            f.write("    ")
        f.write(f"{int(v):8d},")
        if (i + 1) % 8 == 0:
            f.write("\n")
    if len(flat) % 8 != 0:
        f.write("\n")
    f.write("};\n\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=DEFAULT_OUT)
    parser.add_argument("--seed",   type=int, default=42,
                        help="RNG seed for reproducible weights")
    args = parser.parse_args()

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)

    rng = np.random.default_rng(args.seed)
    guard = os.path.basename(args.output).upper().replace(".", "_").replace("-", "_")

    print(f"Generating synthetic INT8 weights (seed={args.seed})")
    print(f"  Network: {' → '.join(str(l[1]) for l in LAYERS)} → {LAYERS[-1][2]}")
    print(f"  Output : {args.output}")
    print()

    scales = []
    layers_data = []

    for idx, (name, in_f, out_f) in enumerate(LAYERS):
        # Xavier-uniform initialisation in float32, then quantize
        limit = np.sqrt(6.0 / (in_f + out_f))
        W_fp  = rng.uniform(-limit, limit, (out_f, in_f)).astype(np.float32)
        b_fp  = np.zeros(out_f, dtype=np.float32)

        W_q, scale = quantize_tensor(W_fp)
        b_q = np.round(b_fp / scale).astype(np.int32)

        scales.append(scale)
        layers_data.append((name, in_f, out_f, W_q, b_q, scale))

        q16 = int(round(scale * 65536))
        print(f"  Layer {idx} ({name}): {out_f}×{in_f}  scale={scale:.6g}  Q16={q16}")

    with open(args.output, "w") as f:
        f.write("/* Auto-generated by gen_weights_numpy.py — synthetic weights for simulation.\n")
        f.write(" * For real MNIST inference run: python3 tools/train_mnist.py --quantize\n")
        f.write(" */\n\n")
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")
        f.write('#include "nn.h"\n\n')

        for idx, (name, in_f, out_f, W_q, b_q, scale) in enumerate(layers_data):
            q16 = int(round(scale * 65536))
            f.write(f"/* Layer {idx} ({name}): {out_f}×{in_f}, scale={scale:.6g} */\n")
            emit_int8(f, f"w{idx}", W_q)
            emit_int32(f, f"b{idx}", b_q)
            f.write(f"#define W{idx}_SCALE_Q16  {q16}u\n\n")

        f.write("/* Network layers — pass to nn_forward(). */\n")
        f.write("static nn_layer_t mnist_net_layers[] = {\n")
        for idx, (name, in_f, out_f, W_q, b_q, scale) in enumerate(layers_data):
            relu = 1 if idx < len(layers_data) - 1 else 0
            f.write(f"    {{ /* [{idx}] {name} */\n")
            f.write(f"        .in_size  = {in_f}u,\n")
            f.write(f"        .out_size = {out_f}u,\n")
            f.write(f"        .weights  = (int8_t  *)(void *)w{idx},\n")
            f.write(f"        .bias     = (int32_t *)(void *)b{idx},\n")
            f.write(f"        .relu     = {relu}u,\n")
            f.write( "    },\n")
        f.write("};\n\n")
        f.write(f"#define MNIST_NET_N_LAYERS  {len(layers_data)}\n\n")

        # 10 synthetic test images (one per digit class), 784 INT8 pixels
        f.write("/* Synthetic 28×28 test images (one per class, seeded). */\n")
        f.write("/* Replace with real MNIST pixels for actual accuracy testing. */\n")
        img_rng = np.random.default_rng(99)
        f.write("static const int8_t test_images[10][784] = {\n")
        for cls in range(10):
            img = img_rng.integers(-64, 64, 784, dtype=np.int8)
            row = "{" + ", ".join(str(int(v)) for v in img) + "}"
            f.write(f"    {row},  /* class {cls} */\n")
        f.write("};\n\n")
        f.write("static const int expected_labels[10] = {0,1,2,3,4,5,6,7,8,9};\n\n")

        f.write(f"#endif /* {guard} */\n")

    print(f"\nWritten: {args.output}")
    size = os.path.getsize(args.output)
    print(f"  File size: {size//1024} KB ({size} bytes)")


if __name__ == "__main__":
    main()
