#!/usr/bin/env python3
"""
gen_test_vectors.py — generate INT8 FC-layer test vectors for nn_fc_forward.

Produces a C header (test_vectors.h) containing:
  - Input INT8 activations
  - INT8 weight matrices
  - INT32 bias vectors
  - Expected INT32 outputs (numpy reference)

The test_nn.c file includes this header and verifies nn_fc_forward output
matches the reference exactly.

Usage:
    python3 tools/gen_test_vectors.py --output sw/nn/test_vectors.h

No PyTorch required — uses numpy only.
"""

import argparse
import numpy as np

CASES = [
    # (in_size, out_size, relu, seed)
    (4,   4,  False, 1),    # T1: minimal 4×4  — exercises one accelerator tile
    (4,   4,  True,  2),    # T2: with ReLU
    (8,   4,  False, 3),    # T3: 2 input tiles, 1 output tile
    (4,   8,  False, 4),    # T4: 1 input tile, 2 output tiles
    (8,   8,  False, 5),    # T5: 2×2 tiles
    (16,  8,  True,  6),    # T6: larger, with ReLU
    (4,   4,  False, 7),    # T7: all-zero weights
    (4,   4,  False, 8),    # T8: all-one activations
]


def ref_fc(w, b, x, relu):
    """Reference INT32 fully-connected layer (numpy, no saturation)."""
    out = w.astype(np.int32) @ x.astype(np.int32) + b.astype(np.int32)
    if relu:
        out = np.maximum(out, 0)
    return out


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="sw/nn/test_vectors.h")
    args = parser.parse_args()

    lines = [
        "/* Auto-generated by gen_test_vectors.py -- do not edit. */",
        "#ifndef TEST_VECTORS_H",
        "#define TEST_VECTORS_H",
        "",
        '#include "nn.h"',
        "",
        f"#define NUM_TEST_CASES  {len(CASES)}",
        "",
    ]

    for idx, (in_sz, out_sz, relu, seed) in enumerate(CASES):
        rng = np.random.default_rng(seed)

        if seed == 7:
            W = np.zeros((out_sz, in_sz), dtype=np.int8)
        elif seed == 8:
            W = np.ones((out_sz, in_sz), dtype=np.int8)
        else:
            W = rng.integers(-128, 127, size=(out_sz, in_sz), dtype=np.int8)

        b   = rng.integers(-256, 256, size=out_sz, dtype=np.int32)
        x   = rng.integers(-128, 127, size=in_sz,  dtype=np.int8)
        ref = ref_fc(W, b, x, relu)

        def fmt_i8(a):
            return "{" + ", ".join(str(int(v)) for v in a.flatten()) + "}"

        def fmt_i32(a):
            return "{" + ", ".join(str(int(v)) for v in a.flatten()) + "}"

        lines += [
            f"/* ── Test case {idx}: {in_sz}→{out_sz} relu={int(relu)} seed={seed} ── */",
            f"static const int8_t  tc{idx}_input[{in_sz}]            = {fmt_i8(x)};",
            f"static int8_t        tc{idx}_weights[{out_sz}][{in_sz}] = {{",
        ]
        for r in range(out_sz):
            lines.append("    " + "{" + ", ".join(str(int(v)) for v in W[r]) + "},")
        lines += [
            "};",
            f"static const int32_t tc{idx}_bias[{out_sz}]            = {fmt_i32(b)};",
            f"static const int32_t tc{idx}_ref[{out_sz}]             = {fmt_i32(ref)};",
            "",
        ]

    # Emit summary struct for the test runner
    lines += [
        "typedef struct {",
        "    uint32_t  in_size;",
        "    uint32_t  out_size;",
        "    uint8_t   relu;",
        "    int8_t   *weights;   /* [out_size][in_size] */",
        "    int32_t  *bias;",
        "    const int8_t   *input;",
        "    const int32_t  *ref;",
        "} test_case_t;",
        "",
        "static test_case_t test_cases[NUM_TEST_CASES] = {",
    ]
    for idx, (in_sz, out_sz, relu, seed) in enumerate(CASES):
        lines.append(
            f"    {{ {in_sz}u, {out_sz}u, {int(relu)}u, "
            f"(int8_t *)tc{idx}_weights, (int32_t *)tc{idx}_bias, "
            f"tc{idx}_input, tc{idx}_ref }},"
        )
    lines += [
        "};",
        "",
        "#endif /* TEST_VECTORS_H */",
    ]

    with open(args.output, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Written {len(CASES)} test cases → {args.output}")
    for idx, (in_sz, out_sz, relu, seed) in enumerate(CASES):
        print(f"  T{idx}: {in_sz}→{out_sz}  relu={relu}  seed={seed}")


if __name__ == "__main__":
    main()
