#!/usr/bin/env python3
"""
quantize.py — INT8 post-training quantization tool for the RISC-V AI SoC.

Loads a trained PyTorch model and exports symmetric per-tensor INT8 weights
as a C header file that can be included directly in SoC firmware.

Usage:
    python3 quantize.py --model mnist_model.pth --output sw/weights_mnist.h
    python3 quantize.py --model mnist_model.pth --output sw/weights_mnist.h \
                        --class-name "mnist_net"

The generated header defines arrays named w0, b0, w1, b1, ... for each
Linear layer found by iterating model.named_modules(). Each layer is also
wrapped in an nn_layer_t initialiser for direct use with sw/nn/nn.h.

Symmetric per-tensor quantization formula:
    scale = max(|W|) / 127
    W_q   = clip(round(W / scale), -128, 127)

Bias is kept as INT32 scaled by the weight scale:
    bias_q = round(bias / scale)

INT8 accuracy degradation is typically < 1% on MNIST, < 3% on CIFAR-10
when using per-tensor quantization. For higher accuracy use per-channel
(add --per-channel flag; not implemented here but straightforward extension).
"""

import argparse
import sys
import os

import numpy as np

try:
    import torch
    import torch.nn as nn
    TORCH_AVAILABLE = True
except ImportError:
    TORCH_AVAILABLE = False


# ── Quantization helpers ─────────────────────────────────────────────────────

def quantize_tensor(t: "torch.Tensor", bits: int = 8) -> tuple:
    """
    Symmetric per-tensor quantization → INT8.

    Returns:
        q      : np.ndarray of dtype int8, same shape as t
        scale  : float, the quantization scale (actual_value = q * scale)
    """
    max_val = float(t.abs().max().item())
    if max_val == 0.0:
        return np.zeros(t.shape, dtype=np.int8), 1.0

    max_int = 2 ** (bits - 1) - 1          # 127 for INT8
    scale   = max_val / max_int
    q_float = np.clip(
        np.round(t.detach().cpu().numpy() / scale),
        -(2 ** (bits - 1)),                # −128
        max_int                            #  127
    )
    return q_float.astype(np.int8), scale


def quantize_bias(bias: "torch.Tensor", scale: float) -> np.ndarray:
    """
    Scale bias into INT32.  Uses the WEIGHT scale so that the accumulator
    output (INT32) is in units of scale², and the output can be rescaled
    by a single factor at requantization time.
    """
    return np.round(bias.detach().cpu().numpy() / scale).astype(np.int32)


# ── C header generation ──────────────────────────────────────────────────────

def emit_array_int8(f, name: str, data: np.ndarray, comment: str = "") -> None:
    f.write(f"/* {comment} */\n" if comment else "")
    f.write(f"static const int8_t {name}[] = {{\n")
    flat = data.flatten()
    for i, v in enumerate(flat):
        if i % 16 == 0:
            f.write("    ")
        f.write(f"{int(v):4d},")
        if (i + 1) % 16 == 0:
            f.write("\n")
    if len(flat) % 16 != 0:
        f.write("\n")
    f.write("};\n\n")


def emit_array_int32(f, name: str, data: np.ndarray, comment: str = "") -> None:
    f.write(f"/* {comment} */\n" if comment else "")
    f.write(f"static const int32_t {name}[] = {{\n")
    flat = data.flatten()
    for i, v in enumerate(flat):
        if i % 8 == 0:
            f.write("    ")
        f.write(f"{int(v):8d},")
        if (i + 1) % 8 == 0:
            f.write("\n")
    if len(flat) % 8 != 0:
        f.write("\n")
    f.write("};\n\n")


def export_model(model, out_path: str, class_name: str) -> None:
    """Export all Linear layers from model to a C header file."""
    linear_layers = [
        (name, mod)
        for name, mod in model.named_modules()
        if isinstance(mod, torch.nn.Linear)
    ]

    if not linear_layers:
        print("[ERROR] No torch.nn.Linear layers found in model.", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(linear_layers)} Linear layer(s):")
    for name, mod in linear_layers:
        print(f"  {name}: ({mod.in_features} → {mod.out_features})")

    guard = os.path.basename(out_path).upper().replace(".", "_").replace("-", "_")

    with open(out_path, "w") as f:
        f.write(f"/* Auto-generated by quantize.py — do not edit manually. */\n")
        f.write(f"/* Model: {class_name}  Layers: {len(linear_layers)} */\n\n")
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")
        f.write('#include "nn.h"\n\n')

        scales = []
        for idx, (name, mod) in enumerate(linear_layers):
            w = mod.weight  # shape: [out_features, in_features]
            b = mod.bias if mod.bias is not None else torch.zeros(mod.out_features)

            w_q, scale = quantize_tensor(w)
            b_q        = quantize_bias(b, scale)
            scales.append(scale)

            # Write row-major: weights[out][in]
            emit_array_int8(
                f, f"w{idx}", w_q,
                f"Layer {idx} ({name}): {mod.out_features}×{mod.in_features} "
                f"INT8 weights (row-major), scale={scale:.6g}"
            )
            emit_array_int32(
                f, f"b{idx}", b_q,
                f"Layer {idx} ({name}): {mod.out_features} INT32 biases, "
                f"scale={scale:.6g}"
            )

            f.write(
                f"/* Scale factor for layer {idx} requantization (Q16 fixed-point). */\n"
                f"/* actual_scale = {scale:.6g}  →  Q16 = {int(round(scale * 65536))} */\n"
                f"#define W{idx}_SCALE_Q16  {int(round(scale * 65536))}u\n\n"
            )

        # Emit nn_layer_t array initialiser
        f.write(f"/* Network definition — pass to nn_forward(). */\n")
        f.write(f"/* ReLU is applied after all layers except the last. */\n")
        f.write(f"static nn_layer_t {class_name}_layers[] = {{\n")
        for idx, (name, mod) in enumerate(linear_layers):
            relu   = 1 if idx < len(linear_layers) - 1 else 0
            cast_w = f"(int8_t  *)(void *)w{idx}"
            cast_b = f"(int32_t *)(void *)b{idx}"
            f.write(
                f"    {{ /* [{idx}] {name} */\n"
                f"        .in_size  = {mod.in_features}u,\n"
                f"        .out_size = {mod.out_features}u,\n"
                f"        .weights  = {cast_w},\n"
                f"        .bias     = {cast_b},\n"
                f"        .relu     = {relu}u,\n"
                f"    }},\n"
            )
        f.write(f"}};\n\n")
        f.write(f"#define {class_name.upper()}_N_LAYERS  {len(linear_layers)}\n\n")

        f.write(f"#endif /* {guard} */\n")

    print(f"\nWritten: {out_path}")
    print(f"  Layers  : {len(linear_layers)}")
    for idx, scale in enumerate(scales):
        print(f"  w{idx} scale: {scale:.6g}  (Q16 = {int(round(scale * 65536))})")


# ── Validation (numpy reference run) ────────────────────────────────────────

def validate_quantized(model, out_path: str, n_samples: int = 32) -> None:
    """
    Run forward pass in both float32 and quantized INT8 and report
    mean absolute error and top-1 match rate on random inputs.
    """
    linear_layers = [
        mod for mod in model.modules()
        if isinstance(mod, torch.nn.Linear)
    ]

    # Collect quantized weights/biases
    layers_q = []
    for mod in linear_layers:
        w_q, scale = quantize_tensor(mod.weight)
        b_q        = quantize_bias(
            mod.bias if mod.bias is not None else torch.zeros(mod.out_features),
            scale
        )
        layers_q.append((w_q.astype(np.float32), b_q.astype(np.float32), scale))

    top1_match = 0
    mae_total  = 0.0
    in_size    = linear_layers[0].in_features

    rng = np.random.default_rng(42)
    for _ in range(n_samples):
        x_np = rng.integers(-128, 127, size=in_size).astype(np.float32)
        x_t  = torch.tensor(x_np, dtype=torch.float32).unsqueeze(0)

        # Float reference
        with torch.no_grad():
            out_f = model(x_t).squeeze(0).numpy()

        # Quantized reference (numpy, mirrors nn_fc_forward tiling logic)
        x_q = x_np.astype(np.int8)
        for li, (w_q, b_q, scale) in enumerate(layers_q):
            # Matrix multiply: [out] = [out×in] @ [in]
            acc = w_q @ x_q.astype(np.float32) + b_q
            is_last = (li == len(layers_q) - 1)
            if not is_last:
                acc = np.maximum(acc, 0)   # ReLU on all but last layer
            x_q = np.clip(acc, -128, 127).astype(np.int8)

        out_q = acc  # last layer output stays INT32-like

        mae       = float(np.abs(out_f - out_q).mean())
        mae_total += mae
        if np.argmax(out_f) == np.argmax(out_q):
            top1_match += 1

    print(f"\nValidation ({n_samples} random samples):")
    print(f"  Mean absolute error : {mae_total / n_samples:.4f}")
    print(f"  Top-1 match rate    : {top1_match}/{n_samples} "
          f"({100*top1_match/n_samples:.1f}%)")


# ── CLI ──────────────────────────────────────────────────────────────────────

def main() -> None:
    if not TORCH_AVAILABLE:
        print("[ERROR] PyTorch is not installed. Install with: pip install torch",
              file=sys.stderr)
        sys.exit(1)

    parser = argparse.ArgumentParser(
        description="INT8 post-training quantization tool for RISC-V AI SoC"
    )
    parser.add_argument("--model",      required=True,
                        help="Path to .pth model file (torch.save state_dict or full model)")
    parser.add_argument("--output",     required=True,
                        help="Output C header file path (e.g. sw/weights_mnist.h)")
    parser.add_argument("--class-name", default="net",
                        help="C identifier prefix for arrays and layer struct (default: net)")
    parser.add_argument("--validate",   action="store_true",
                        help="Run numpy forward-pass validation after export")
    parser.add_argument("--model-class", default=None,
                        help="Python import path for model class if .pth is a state dict "
                             "(e.g. 'mymodels.MnistMLP'). Model must accept no-arg __init__.")
    args = parser.parse_args()

    # Load model
    checkpoint = torch.load(args.model, map_location="cpu")

    if isinstance(checkpoint, torch.nn.Module):
        model = checkpoint.eval()
    elif isinstance(checkpoint, dict) and args.model_class:
        # Import and instantiate model class, then load state dict
        parts  = args.model_class.rsplit(".", 1)
        module = __import__(parts[0], fromlist=[parts[1]])
        cls    = getattr(module, parts[1])
        model  = cls().eval()
        model.load_state_dict(checkpoint)
    else:
        print(
            "[ERROR] .pth file contains a state dict but --model-class was not provided.\n"
            "        Use --model-class module.ClassName to specify the model architecture.",
            file=sys.stderr
        )
        sys.exit(1)

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    export_model(model, args.output, args.class_name.replace("-", "_"))

    if args.validate:
        validate_quantized(model, args.output)


if __name__ == "__main__":
    main()
