/* Auto-generated by gen_test_vectors.py -- do not edit. */
#ifndef TEST_VECTORS_H
#define TEST_VECTORS_H

#include "nn.h"

#define NUM_TEST_CASES  8

/* ── Test case 0: 4→4 relu=0 seed=1 ── */
static const int8_t  tc0_input[4]            = {40, -15, 76, -66};
static int8_t        tc0_weights[4][4] = {
    {126, 99, -95, -8},
    {114, 60, -123, 2},
    {-27, 39, -47, 64},
    {58, 21, -48, 114},
};
static const int32_t tc0_bias[4]            = {-239, -183, 165, 229};
static const int32_t tc0_ref[4]             = {-3376, -6003, -9296, -8938};

/* ── Test case 1: 4→4 relu=1 seed=2 ── */
static const int8_t  tc1_input[4]            = {84, 99, 57, -44};
static int8_t        tc1_weights[4][4] = {
    {64, -41, -22, 85},
    {-57, -126, 120, -63},
    {-29, -16, 122, -102},
    {-30, 105, -24, -53},
};
static const int32_t tc1_bias[4]            = {-45, 160, -25, -209};
static const int32_t tc1_ref[4]             = {0, 0, 7397, 8630};

/* ── Test case 2: 8→4 relu=0 seed=3 ── */
static const int8_t  tc2_input[8]            = {97, 72, -121, 30, -103, -102, 34, -7};
static int8_t        tc2_weights[4][8] = {
    {119, 65, 61, 78, 18, -103, 108, -108},
    {116, 82, 110, -84, -124, 28, 30, -69},
    {-75, 107, -20, -83, 70, -47, -97, 76},
    {-93, -122, 5, 93, -72, 17, -121, 20},
};
static const int32_t tc2_bias[4]            = {-236, -208, -86, -35};
static const int32_t tc2_ref[4]             = {24026, 12537, -5973, -14227};

/* ── Test case 3: 4→8 relu=0 seed=4 ── */
static const int8_t  tc3_input[4]            = {16, 88, -117, 44};
static int8_t        tc3_weights[8][4] = {
    {-51, -90, 119, 56},
    {122, -98, -21, 112},
    {52, -88, 34, 96},
    {75, -37, 101, 1},
    {66, 13, 63, 111},
    {3, -102, 106, 120},
    {-75, 43, -29, 119},
    {-19, 42, 48, -109},
};
static const int32_t tc3_bias[8]            = {-24, 54, -112, -64, 65, 154, 41, -167};
static const int32_t tc3_ref[8]             = {-20219, 767, -6778, -13893, -222, -15896, 11254, -7187};

/* ── Test case 4: 8→8 relu=0 seed=5 ── */
static const int8_t  tc4_input[8]            = {60, 52, -65, -57, -121, 56, -41, -18};
static int8_t        tc4_weights[8][8] = {
    {39, 100, 55, 42, 109, 42, -109, 77},
    {116, 24, 75, -124, -92, -76, 84, 77},
    {63, 44, -123, -9, -66, -33, 107, 2},
    {-11, -125, -42, 32, -5, -58, -87, -56},
    {108, -113, 65, 121, -119, -26, 77, -116},
    {14, -127, -91, -58, 4, -11, -93, -31},
    {67, -94, -72, 17, -79, 50, 16, -25},
    {77, -76, 12, -96, 52, -90, 22, -118},
};
static const int32_t tc4_bias[8]            = {-256, -232, -180, 255, -159, 78, 128, -136};
static const int32_t tc4_ref[8]             = {-6439, 12215, 16111, -4067, 1197, 6806, 15124, -4886};

/* ── Test case 5: 16→8 relu=1 seed=6 ── */
static const int8_t  tc5_input[16]            = {-33, -88, -101, 10, -115, 60, 32, 31, -19, -75, 126, 67, -74, 101, -52, -98};
static int8_t        tc5_weights[8][16] = {
    {125, 1, 109, -16, 16, -94, 68, 8, 94, -113, 11, 3, 6, 24, 95, -42},
    {110, -78, -75, 113, 75, -81, -6, -35, -28, -78, -32, 39, -97, -124, 94, -34},
    {-20, 32, -84, -14, 98, -80, 72, 123, 82, 116, 64, -82, 40, -49, 123, 32},
    {105, -37, -51, -20, -69, -3, 31, 43, 72, -3, -12, 64, -88, -5, -9, -45},
    {-8, 95, -103, 43, -11, -108, -114, 45, -3, 97, 48, -14, -105, -99, -6, -98},
    {-108, -59, -108, 29, -2, -97, -67, -116, -109, 27, 75, 97, 92, -94, 37, 88},
    {102, -127, 36, 87, 88, 125, -59, -127, -37, 116, 50, 119, 76, 1, 15, 121},
    {-25, -86, 123, 20, -28, -9, 53, 82, -29, -65, -3, 67, 93, 20, -126, 72},
};
static const int32_t tc5_bias[8]            = {-178, -232, -121, -150, 24, 179, 126, -35};
static const int32_t tc5_ref[8]             = {0, 0, 0, 27190, 872, 0, 0, 7224};

/* ── Test case 6: 4→4 relu=0 seed=7 ── */
static const int8_t  tc6_input[4]            = {-31, 120, -119, 19};
static int8_t        tc6_weights[4][4] = {
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
};
static const int32_t tc6_bias[4]            = {227, 64, 94, 203};
static const int32_t tc6_ref[4]             = {227, 64, 94, 203};

/* ── Test case 7: 4→4 relu=0 seed=8 ── */
static const int8_t  tc7_input[4]            = {100, -6, -113, -84};
static int8_t        tc7_weights[4][4] = {
    {1, 1, 1, 1},
    {1, 1, 1, 1},
    {1, 1, 1, 1},
    {1, 1, 1, 1},
};
static const int32_t tc7_bias[4]            = {112, -89, -136, 249};
static const int32_t tc7_ref[4]             = {9, -192, -239, 146};

typedef struct {
    uint32_t  in_size;
    uint32_t  out_size;
    uint8_t   relu;
    int8_t   *weights;   /* [out_size][in_size] */
    int32_t  *bias;
    const int8_t   *input;
    const int32_t  *ref;
} test_case_t;

static test_case_t test_cases[NUM_TEST_CASES] = {
    { 4u, 4u, 0u, (int8_t *)tc0_weights, (int32_t *)tc0_bias, tc0_input, tc0_ref },
    { 4u, 4u, 1u, (int8_t *)tc1_weights, (int32_t *)tc1_bias, tc1_input, tc1_ref },
    { 8u, 4u, 0u, (int8_t *)tc2_weights, (int32_t *)tc2_bias, tc2_input, tc2_ref },
    { 4u, 8u, 0u, (int8_t *)tc3_weights, (int32_t *)tc3_bias, tc3_input, tc3_ref },
    { 8u, 8u, 0u, (int8_t *)tc4_weights, (int32_t *)tc4_bias, tc4_input, tc4_ref },
    { 16u, 8u, 1u, (int8_t *)tc5_weights, (int32_t *)tc5_bias, tc5_input, tc5_ref },
    { 4u, 4u, 0u, (int8_t *)tc6_weights, (int32_t *)tc6_bias, tc6_input, tc6_ref },
    { 4u, 4u, 0u, (int8_t *)tc7_weights, (int32_t *)tc7_bias, tc7_input, tc7_ref },
};

#endif /* TEST_VECTORS_H */
