/* keyword_spotting/main.c — MFCC + LSTM keyword spotting on RV32 AI SoC
 *
 * Keywords: "yes", "no", "stop", "go" (4-class, background = class 4).
 * Target: < 20 ms per 1-second audio window at 100 MHz.
 *
 * Pipeline:
 *   1. Read 16 kHz PCM from SPI ADC (I2S not available; use SPI + CS)
 *   2. Compute 40-bin MFCC via SW FFT (frame = 25 ms, hop = 10 ms)
 *   3. Run 1×LSTM + 1×FC on MFCCs using the AI accelerator
 *   4. Output class label over UART
 *
 * Weights: weights_kws_int4.h (generated by tools/onnx_to_c.py)
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <math.h>
#include "uart.h"
#include "accel.h"
#include "soc.h"
#include "weights_kws_int4.h"

#define SAMPLE_RATE_HZ  16000
#define FRAME_LEN       400     /* 25 ms at 16 kHz */
#define FRAME_HOP       160     /* 10 ms at 16 kHz */
#define NUM_MELS        40
#define NUM_FRAMES      98      /* 1 s / 10 ms hop */
#define LSTM_HIDDEN     64
#define NUM_CLASSES     5       /* yes/no/stop/go/background */

static const char *class_names[NUM_CLASSES] = {
    "yes", "no", "stop", "go", "<background>"
};

/* ── Minimal MFCC: log-mel filterbank (no DCT — mel spectrogram) ──────── */
/* In production: replace with a lookup-table-based FFT for performance.    */
static void compute_mfcc(const int16_t *pcm, int32_t mfcc[NUM_FRAMES][NUM_MELS]) {
    /* Simplified: just compute energy in NUM_MELS frequency bins via
     * rectangular filterbank + log. Real deployment uses 512-pt FFT. */
    (void)pcm;
    /* Placeholder — real implementation in tools/mfcc.c */
    memset(mfcc, 0, sizeof(int32_t) * NUM_FRAMES * NUM_MELS);
}

/* ── LSTM step (INT4 via accelerator) ────────────────────────────────────── */
static void lstm_step(const int32_t *x, int32_t *h, int32_t *c) {
    static int32_t gates[4 * LSTM_HIDDEN];
    /* gates = Wx * x + Wh * h + b  (packed into one matmul) */
    accel_matmul_int4(lstm_wx, (const int4x2_t *)x, gates,
                      4 * LSTM_HIDDEN, 1, NUM_MELS);
    accel_matmul_int4(lstm_wh, (const int4x2_t *)h, gates,
                      4 * LSTM_HIDDEN, 1, LSTM_HIDDEN);
    /* Simplified LSTM update (tanh/sigmoid approximated as clamp for INT4) */
    for (int i = 0; i < LSTM_HIDDEN; i++) {
        int32_t f = (gates[i]               + lstm_b[i])               > 0 ? 1 : 0;
        int32_t in_g = (gates[LSTM_HIDDEN+i]   + lstm_b[LSTM_HIDDEN+i])   > 0 ? 1 : 0;
        int32_t g = gates[2*LSTM_HIDDEN+i]  + lstm_b[2*LSTM_HIDDEN+i];
        int32_t o = (gates[3*LSTM_HIDDEN+i] + lstm_b[3*LSTM_HIDDEN+i]) > 0 ? 1 : 0;
        c[i] = f * c[i] + in_g * g;
        h[i] = o * (c[i] > 0 ? c[i] : 0);
    }
}

int main(void) {
    uart_init(115200);
    accel_init();

    printf("Keyword spotting demo (say: yes/no/stop/go)\r\n");
    printf("Listening for 1-second windows...\r\n\r\n");

    static int16_t  pcm[SAMPLE_RATE_HZ];
    static int32_t  mfcc[NUM_FRAMES][NUM_MELS];
    static int32_t  h[LSTM_HIDDEN], c[LSTM_HIDDEN];
    static int32_t  logits[NUM_CLASSES];

    int window = 0;
    while (1) {
        /* Read PCM from SPI ADC (stub: in real HW, use DMA + SPI ADC) */
        memset(pcm, 0, sizeof(pcm));

        uint32_t t0 = CSR_READ(mcycle);

        compute_mfcc(pcm, mfcc);

        memset(h, 0, sizeof(h));
        memset(c, 0, sizeof(c));
        for (int t = 0; t < NUM_FRAMES; t++)
            lstm_step(mfcc[t], h, c);

        /* Final FC layer */
        accel_matmul_int4(fc_weights, (const int4x2_t *)h, logits,
                          NUM_CLASSES, 1, LSTM_HIDDEN);
        for (int i = 0; i < NUM_CLASSES; i++) logits[i] += fc_bias[i];

        uint32_t cycles = CSR_READ(mcycle) - t0;
        uint32_t ms_x10 = (cycles * 10UL) / (CPU_HZ / 1000UL);

        int pred = 0;
        for (int i = 1; i < NUM_CLASSES; i++)
            if (logits[i] > logits[pred]) pred = i;

        printf("[%3d] %s  (%u.%u ms)\r\n",
               ++window, class_names[pred], ms_x10/10, ms_x10%10);
    }
}
